### ISSUE TITLE
Silhouette Loss Question

### ISSUE THREAD

**Issue by whateverforever** [leonidk/fuzzy-metaballs#1]
Hey there, thank you for this exciting project!
I have one question regarding the silhouette loss for pose estimation: How would I use this in a real-world case, where I don't know the true silhouette, and can't infer it from the depth data? Currently, the only way I see, is to estimate it with a NN.

Mitsuba's pose estimation demo just uses the a mean squared pixel wise error, but I don't think that is directly applicable here. Did you experiment with other measures?

**Comment by leonidk** [comment]
Hi, sorry for the late reply. I thought github issues would produce emails but I guess they don't? 

Yes, in this project I was just interested in modeling shape, so I wanted a shape-based loss (silhouette or depth). I would recommend using a neural network, for example, propagating an existing mask ([XMem](https://github.com/hkchengrex/XMem)) or generating your own per-image masks ([Detic](https://github.com/facebookresearch/Detic)). 

I'm currently refactoring the code, but when that's done, I can hopefully share a version that uses color. But the addition is straightforward: just re-use the weights from the rendering to do a weighted average of per-blob colors. I'll keep open until I upload something like this.

**Comment by leonidk** [comment]
Hi @whateverforever . I updated the example with color rendering in co3d. This doesn't include my XMem pipeline, but should be a better illustration for typical reconstructions.

**Comment by whateverforever** [comment]
Hi @leonidk thank you, I will give it a try one of these days!
