### ISSUE TITLE
Package requirements with versions

### ISSUE THREAD

**Issue by mrdaybird** [leonidk/fuzzy-metaballs#2]
First of all, very exciting project!
But I having trouble setting up proper environment to reproduce the code. The jax and pytorch3d libraries having lots of conflicts due to different requirements for pytorch and cudatoolkit versions. 
Can you provide the what versions of the jax, pytorch3d, pytorch and cuda were used by you?

**Comment by leonidk** [comment]
Yes, my bad. I should add a requirements.txt file... Here's what I have on my two different machines.

jax 0.3.17
jaxlib 0.3.15
pytorch3d  0.7.0
torch 1.12.1

torch 1.11.0+cu113
jax 0.3.1
jaxlib 0.3.0+cuda11.cudnn82
pytorch3d 0.6.1 py39_cu113_pyt1100

Next time I push an update, I'll add a requirements.txt file that works. Will retain issue until then

**Comment by leonidk** [comment]
Hi @mrdaybird. 

I updated the project and replaced the torch renderer with pyrender, which should be simpler and easier to get running.
